spring:
  application:
    name: seoulArt

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: EFSiWGS4Omrh4Tv4ZHgm
            client-secret: TpgP7auqTu
            redirect-uri: "http://localhost:5173/oauth/callback/naver"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
                        
          kakao:
            client-id: "506825a69a9d9a83db0f7f1f8aaffe7d" # 앱키 -> REST API 키
            client-secret: Flejpx0RTQrq2fvNfbyENG0JWfFpqUwh # 카카오 로그인 -> 보안 -> Client Secret 코드
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:5173/oauth/callback/kakao" # yml 파일에서 {} 가 spring 특수문자로 인식되게 하기 위해 " " 사용  이 부분 로컬 -> seoulart 로 바꿨음
            client-authentication-method: client_secret_post    # POST  로 바꿔봐야함
            scope: profile_nickname,account_email,profile_image   # 가져오는 리스트(스코프) : 필수항목
       
            

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # "인가 코드 받기" 항목
            token-uri: https://kauth.kakao.com/oauth/token # "토큰 받기" 항목
            user-info-uri: https://kapi.kakao.com/v2/user/me # "사용자 정보 가져오기" 항목
            user-name-attribute: id # 식별자 . 카카오의 경우 "id" 사용
            
            
  # MySQL 연결 설정
  datasource:
    url: jdbc:mysql://database-1.cls4oq20gmca.ap-northeast-2.rds.amazonaws.com:3306/seoulArtDB
    username: admin
    password: admin1013
    driver-class-name: com.mysql.cj.jdbc.Driver

# jpa설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
      
      
  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
seoulArt:
  secret-key: "THISISSKYBORYYUMYUMDEVELOPINGTHANKYOU"
